name: c-compiler

services:
  alpine:
    container_name: c-compiler-alpine
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    environment:
      - WHOAMI=c-compiler
    volumes:
      - ./src:/home/c-compiler/src
