name: c-compiler

services:
  ubuntu:
    container_name: c-compiler-ubuntu
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WHOAMI=user
    tty: true
    stdin_open: true
    environment:
      - WHOAMI=user
    volumes:
      - ./src:/home/user/src
