name: c-compiler

services:
  ubuntu:
    container_name: c-compiler-ubuntu
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WHOAMI=c-compiler
    tty: true
    stdin_open: true
    environment:
      - WHOAMI=c-compiler
    volumes:
      - ./src:/home/c-compiler/src
